### ISSUE TITLE
Score calculation is broken

### ISSUE THREAD

**Issue by delvh** [Dudrie/Tutor-Management-System#1023]
TMS can't calculate the score of exercises and exercise sheets anymore in the PDFs and the exercise sheet-specific statistics.
The calculation always returns zero, even if points have been entered:
![image](https://user-images.githubusercontent.com/51889757/200072491-e27a5701-61e3-41ec-8645-05c990d8bddc.png)
![image](https://user-images.githubusercontent.com/51889757/200072722-9424d228-87d6-465f-828a-4a4fca9bdb44.png)

EDIT: The problem is even weirder. Only specific exercises are being counted:
![image](https://user-images.githubusercontent.com/51889757/200076836-f0c10223-98aa-49e0-9d5b-6a92e7e65a29.png)

# :heavy_check_mark: Expected behaviour

The score calculation should work as intended

# :joystick: Steps to reproduce

1. Enter points for a team in an exercise
2. Go back one page to the team summary page of this exercise
3. (optional, click on `PDF Preview`)
6. Aaaand... broken...

**Comment by nk-coding** [comment]
This is caused by the grading entity only summing up the points of each exercise.
Currently, if an exercise has SubExercises, their points are saved in the subExercisePoints, but not in points itself. 
So there are 2 possible solutions:
- always also persist the sum of all sub-exercise points in points (this is likely bad design, also this would require migrations)
- change the sum logic, so that it also sums up all subExercisePoints
  - what if both are set? is this an allowed use case? otherwise we maybe should validate on update that subExercisePoints are correctly set (not at all if no sub exercises, and if present the correct length)
